version: 2

sources:
  - name: Supermarket
    database: talleractivity2
    tables:
      - name: Clientes_EXT
        description: Vista externa, proveniente de Google Sheets, con la información de los clientes. 
      - name: Compras_EXT
        description: Vista externa, proveniente de Google Drive, con la información histórica de compras. 
      - name: Exito_EXT
        description: Vista externa, proveniente de Google Sheets, con la información de los productos de Éxito.
      - name: Olimpica_EXT
        description: Vista externa, proveniente de Google Sheets, con la información de los productos de Olímpica.
models:
  - name: Olimpica
    description: "Transformación de vista externa a tabla cargada en BQ de la tabla con los productos de Olímpica"
    columns:
      - name: Codigo
        description: "Clave primaria. Código único de cada producto"
      - name: Producto
        description: "Descripción del producto. Información relacionada."
      - name: Cantidad
        description: "Cantidad del producto"
      - name: Unidad
        description: "Unidad de medida del producto"
      - name: Precio
        description: "Precio del producto"

  - name: Exito
    description: "Transformación de vista externa a tabla cargada en BQ de la tabla con los productos de Exito"
    columns:
      - name: Codigo
        description: "Clave primaria. Código único de cada producto"
      - name: Producto
        description: "Descripción del producto. Información relacionada."
      - name: Cantidad
        description: "Cantidad del producto"
      - name: Unidad
        description: "Unidad de medida del producto"
      - name: Precio
        description: "Precio del producto"

  - name: Clientes
    description: "Transformación de vista externa a tabla cargada en BQ con la información de los clientes"
    columns:
      - name: Codigo
        description: "Clave primaria. Código único de cada cliente"
      - name: Apellido
        description: "Apellido del cliente"
      - name: Nombre
        description: "Nombre del cliente"
      - name: Email
        description: "Dirección de correo electrónico del cliente"
      - name: Celular
        description: "Número de celular del cliente"
      - name: Edad
        description: "Edad del cliente"
      - name: Latitud
        description: "Latitud de la ubicación del cliente"
      - name: Longitud
        description: "Longitud de la ubicación del cliente"

  - name: Compras
    description: "Transformación de vista externa a tabla cargada en BQ con el histórico de Compras en ambos almacenes"
    columns:
      - name: cliente
        description: "Código de cliente que efectuó la compra"
      - name: producto
        description: "Código de producto de la compra"
      - name: fecha
        description: "Fecha de la compra"

  - name: comprobacionOlimpica
    description: "Comprueba si la tabla Olimpica contiene campos nulos en alguna de sus columnas"

  - name: comprobacionExito
    description: "Comprueba si la tabla Exito contiene campos nulos en alguna de sus columnas"

  - name: comprobacionClientes
    description: "Comprueba si la tabla Clientes contiene campos nulos en alguna de sus columnas"

  - name: comprobacionCompras
    description: "Comprueba si la tabla Compras contiene campos nulos en alguna de sus columnas"

  - name: cantidadTotal
    description: "Suma la cantidad de productos en la tabla Olimpica, referente a los productos de Olimpica"
    
  - name: rowId
    description: "Agrega un id único a cada producto"
    
  - name: median
    description: "Cálculo de la mediana"

  - name: Olimpica_IMP
    description: "Imputación por la mediana"
    
  - name: compras
    description: "Total de tabla compras"
  
  - name: productosExito
    description: "Total de productos de Éxito con su información"
  
  - name: productosOlimpica
    description: "Total de productos de Olímpica con su información"

  - name: productos
    description: "Total de productos de ambas tiendas con su información"

  - name: punto5
    description: "Solución al punto 5. Productos que nunca han sido comprados"

  - name: cruceProductos
    description: "Productos de vino tinto con sus cantidades compradas y su información, incluyendo gasto, que es cantidadComprada * precio"

  - name: promedio
    description: "Promedio de compras de vino tinto entre todas las variantes de vino tinto disponibles"  
    
  - name: vinoTintoAmbos
    description: "Unión de los productos de vino tinto de ambas tiendas"

  - name: vinoTintoExi
    description: "productos de vino tinto de Éxito"
  
  - name: vinoTintoOli
    description: "productos de vino tinto de Olímpica"

  - name: punto1
    description: "Solución al punto 1. Promedio de compras de vino tinto"

  - name: comprasTotales
    description: "Total de compras en la tabla histórica"

  - name: preciosExito
    description: "Total de precios de éxito por código de producto"

  - name: preciosOlimpica
    description: "Total de precios de olímpica por código de producto"

  - name: ventasExito
    description: "Total de ventas de éxito por código de producto"

  - name: ventasOlimpica
    description: "Total de ventas de olímpica por código de producto"

  - name: ventasTotales
    description: "Total de ventas totales en ambas tiendas"

  - name: punto2
    description: "Solución al punto 2. Compradores destacados en Olímpica y Éxito"

  - name: comprasExito
    description: "Total de compras, obtenidas de la tabla Compras, pertenecientes a Éxito"

  - name: comprasOlimpica
    description: "Total de compras, obtenidas de la tabla Compras, pertenecientes a Olímpica"

  - name: punto3
    description: "Solución al punto 3. Clientes que han comprado en Olímpica pero no en Éxito"

  - name: cruceInformacion
    description: "Cruce de tablas para juntar el número de compras de cada producto con su información"

  - name: punto4
    description: "Ordenar por frecuencia los productos principales más comprados, de mayor a menor cantidad de compras. Limitado al TOP 10"