dbt-ta2:
  outputs:
    dev:
      dataset: Supermarket
      job_execution_timeout_seconds: 1200
      job_retries: 1
      keyfile: dbt-test\key.json
      location: US
      method: service-account
      priority: interactive
      project: talleractivity2
      threads: 1
      type: bigquery
  target: dev

another-profile:
  outputs:
    dev:
    prod:
  target: dev